version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: |
          sudo pip3 install awscli

          mkdir -p ~/.local/bin
          curl https://releases.hashicorp.com/terraform/0.13.2/terraform_0.13.2_linux_amd64.zip -o terraform.zip
          unzip terraform.zip -d ~/.local/bin
          rm terraform.zip

          curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip
          unzip tflint.zip -d ~/.local/bin
          rm tflint.zip
      - run: make test
