version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - run: sudo pip install awscli
      - run: make test
