---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Issue certificate for cloudfront for custom domain
Parameters:
  DomainName:
    Type: String
    Description: FQDN
  ValidationDomain:
    Type: String
    Description: FQDN
  HostedZoneId:
    Type: String
    Description: HostedZoneId for the ValidationDomain
Conditions:
  HasHostedZoneId: !Not [!Equals [!Ref HostedZoneId, "null"]]
Resources:
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - Fn::If:
            - HasHostedZoneId
            - DomainName: !Ref DomainName
              HostedZoneId: !Ref HostedZoneId
            - DomainName: !Ref DomainName
              ValidationDomain: !Ref ValidationDomain
      ValidationMethod:
        Fn::If:
          - HasHostedZoneId
          - "DNS"
          - "Email"
