
---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Static website only for redirection
Parameters:
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: '(?!-)[a-zA-Z0-9-.]{1,63}(?<!-)'
    ConstraintDescription: must be a valid DNS zone name.
  RedirectTo:
    Type: String
    Description: FQDN
  RedirectFrom:
    Type: String
    Description: FQDN
  RedirectProtocol:
    Type: String
    Description: protocol
    Default: https
    AllowedValues:
      - http
      - https
Mappings:
  Region2S3WebsiteSuffix:
    us-east-1:
      Suffix: .s3-website-us-east-1.amazonaws.com
    us-west-1:
      Suffix: .s3-website-us-west-1.amazonaws.com
    us-west-2:
      Suffix: .s3-website-us-west-2.amazonaws.com
    eu-west-1:
      Suffix: .s3-website-eu-west-1.amazonaws.com
    eu-west-2:
      Suffix: .s3-website-eu-west-2.amazonaws.com
    eu-west-3:
      Suffix: .s3-website-eu-west-3.amazonaws.com
    ap-northeast-1:
      Suffix: .s3-website-ap-northeast-1.amazonaws.com
    ap-northeast-2:
      Suffix: .s3-website-ap-northeast-2.amazonaws.com
    ap-northeast-3:
      Suffix: .s3-website-ap-northeast-3.amazonaws.com
    ap-southeast-1:
      Suffix: .s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      Suffix: .s3-website-ap-southeast-2.amazonaws.com
    ap-south-1:
      Suffix: .s3-website-ap-south-1.amazonaws.com
    us-east-2:
      Suffix: .s3-website-us-east-2.amazonaws.com
    ca-central-1:
      Suffix: .s3-website-ca-central-1.amazonaws.com
    sa-east-1:
      Suffix: .s3-website-sa-east-1.amazonaws.com
    cn-north-1:
      Suffix: .s3-website.cn-north-1.amazonaws.com.cn
    cn-northwest-1:
      Suffix: .s3-website.cn-northwest-1.amazonaws.com.cn
    eu-central-1:
      Suffix: .s3-website-eu-central-1.amazonaws.com
Resources:
  S3BucketForWebsiteContent:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RedirectTo
          Protocol: !Ref RedirectProtocol
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for S3-backed website
        Aliases:
          - !Ref RedirectFrom
        Enabled: 'true'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
        Origins:
        - CustomOriginConfig:
            OriginProtocolPolicy: match-viewer
          DomainName:
            !Join
            - ''
            - - !Ref S3BucketForWebsiteContent
              - !FindInMap
                - Region2S3WebsiteSuffix
                - !Ref AWS::Region
                - Suffix
          Id: only-origin
  WebsiteDNSName:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt
          - WebsiteCDN
          - DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
      HostedZoneName:
        !Join
        - ''
        - - !Ref HostedZone
          - "."
      Comment: CNAME redirect custom name to CloudFront distribution
      Name: !Ref RedirectFrom
      Type: A

  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref RedirectFrom
      DomainValidationOptions:
        - DomainName: !Ref RedirectFrom
          ValidationDomain: !Ref HostedZone
      
Outputs:
  BucketName:
    Value: !Ref S3BucketForWebsiteContent
    Description: Name of S3 bucket to hold website content
  BucketURL:
    Value: !Join
      - ""
      - - "http://"
        - !Ref S3BucketForWebsiteContent
        - !FindInMap [ Region2S3WebsiteSuffix, !Ref 'AWS::Region', Suffix]

    Description: Name of S3 bucket to hold website content
  #WebsiteURL:
  #  Value: !Join
  #  - ''
  #  - - http://
  #    - !Ref WebsiteDNSName
