---
AWSTemplateFormatVersion: 2010-09-09
Description: S3Bucket
Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket Name

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName

Outputs:
  S3Bucket:
    Value: !Ref S3Bucket